Plat 20 primera seccion landing page using tailwind
ProgramadoresArgentina/proyecto-ada pull request #13
Opened 2023-01-17 20:22 UTC by SmaelNicolas

# Descripción

Created Hero section with components and imported in index
Imported fonts
added domain for dummy  avatar images

## Jira

[- Link de la tarjeta del _JIRA_ asociada.](https://programadores-argentina.atlassian.net/browse/PLAT-20)

## Preview

[- Preview.](https://proyecto-me4svczzt-programadores-argentina.vercel.app/)

2023-01-18 01:56 UTC, neriheredia requested changes

2023-01-18 01:56 UTC, neriheredia commented on components/Hero/Hero_Paragraph.tsx
> +			programadores de Argentina.
una pequeña corrección, comun le falta el acento, común.

2023-01-18 01:56 UTC, neriheredia commented on components/Hero/Hero_Image.tsx
> +			/>
Creo que sería mejor acomodar las propiedades en orden alfabético, ya que es más fácil para otro dev encontrar lo que está buscando.

2023-01-18 01:56 UTC, neriheredia commented on components/Hero/Hero_Avatars.tsx
> +					className="-ml-4 rounded-full"
Aquí también, orden alfabético, por favor

2023-01-18 01:56 UTC, neriheredia commented on components/Hero/Hero_Avatars.tsx
> +
¿Te parece si creamos a la altura del root una carpeta, models o interface y la colocamos ahí? Ya que podríamos después reutilizarlo en otro lado de la aplicación o extender su interfaz

2023-01-18 01:56 UTC, neriheredia commented on components/Hero/Hero_Pattern.tsx
> +		<div className="w-[300px] h-[80px] md:w-[400px] md:h-[140px] background-pattern flex justify-center items-center absolute bottom-0 -left-5 md:-left-14 -z-10 "></div>
Ya que no lleva contenido entro 2 tags, se podría cerrar directamente el div. Por ejemplo, así <div />

2023-01-18 01:56 UTC, neriheredia commented on pages/index.tsx
> +};
Se podría hacer un return implícito, ya que no se utilizan estados u funciones dentro del componente. Por ejemplo,
const Home: NextPage = () => (
            <div>
                 <Hero />
            </div>
)

Revisa en los otros componentes que puedes hacer lo mismo. ¡Gracias! ¡Y excelente trabajo!

2023-01-18 01:56 UTC, neriheredia commented on components/Hero/Hero_Button.tsx
> +			<button className="bg-shadeBlue hover:bg-shadeBlueHover ease-in duration-100 text-white font-normal tracking-tight md:tracking-normal text-xs min-[360px]:text-sm md:text-base rounded-full py-3 mt-
Creo que la condiciona se podría solo preguntando si existe sizeScreen. Por ejemplo:
{
   !sizeScreen && ( Componente )
}

2023-01-18 01:58 UTC, neriheredia commented
![Captura de pantalla de 2023-01-17 22-37-14](https://user-images.githubusercontent.com/82787982/213062415-29ee4fd5-f966-4fee-91a5-16de8a3337a8.png)
Mira entre 1000 y 1100 antes de desaparecer la imagen, se achica de esta manera. Creo que lo mejor sería hacerla desaparecer antes y que no suceda eso. ¿Qué opinas?

2023-01-23 00:45 UTC, neriheredia commented on components/Hero/Hero_Button.tsx
> +			<button className="bg-shadeBlue hover:bg-shadeBlueHover ease-in duration-100 text-white font-normal tracking-tight md:tracking-normal text-xs min-[360px]:text-sm md:text-base rounded-full py-3 mt-
@SmaelNicolas Quisiera saber si probaste cambiando el hook a null.

2023-01-23 01:20 UTC, SmaelNicolas commented on components/Hero/Hero_Button.tsx
> +			<button className="bg-shadeBlue hover:bg-shadeBlueHover ease-in duration-100 text-white font-normal tracking-tight md:tracking-normal text-xs min-[360px]:text-sm md:text-base rounded-full py-3 mt-
Hola @neriheredia  , si lo probe .
Cambie a null el hook y a !sizeScreen pero no se muestra , ni al hacer resize.
Por ahi hay alguna manera pero no la estaria viendo, esta es la unica que encontre que me funciono.

2023-01-23 01:40 UTC, neriheredia requested changes

2023-01-23 01:40 UTC, neriheredia commented on components/Hero/Hero.tsx
> +};
Podríamos hacer un return implícito ahí que te parece @SmaelNicolas

2023-01-23 02:03 UTC, neriheredia approved these changes
Excelente trabajo Nicolás. Aprobado!

2023-02-10 18:15 UTC, JuanseMastrangelo approved these changes

2023-02-10 18:15 UTC, merged