Plat 15 develop navigation bar
ProgramadoresArgentina/proyecto-ada pull request #14
Opened 2023-01-19 05:38 UTC by sampxcs

# Descripción
Desarrollo de un navegador en la parte superior del sitio.

## Jira
https://programadores-argentina.atlassian.net/browse/PLAT-15?atlOrigin=eyJpIjoiMDhiNmJkZDRlMGVlNDgzYjliM2U1MTllZDVkZjE3MWQiLCJwIjoiaiJ9

2023-01-19 10:28 UTC, neriheredia requested changes
Excelente trabajo esas pequeñas cositas. Saludos

2023-01-19 10:28 UTC, neriheredia commented on components/NavBar/NavHamburguerButton.tsx
> +}
Cambiaría el nombre a NavHamburguerProps y crearía una carpeta a la altura de root Interfaces o Models para guardarlo así después reutilizarlo o extenderlo. Que te parece Ian?

2023-01-19 10:28 UTC, neriheredia commented on components/NavBar/NavHamburguerButton.tsx
> +      <span className={`w-full bg-black h-0.5 transition-all rounded-sm ${active && 'translate-y-[-8px] rotate-[45deg]'}`}></span>
Si entre medio de los tags no va a tener contenido es mejor cerrarlo en el mismo tag. Ejemplo <span />

2023-01-19 10:28 UTC, neriheredia commented on components/NavBar/NavLink.tsx
> +}
Lo mismo aquí cambiar el nombre y lo de la carpeta

2023-01-19 10:28 UTC, neriheredia commented on components/NavBar/index.tsx
> +      <div className='w-full h-full bg-white absolute top-0 z-10 left-0'></div>
Cerrar en un solo tag

2023-01-19 10:28 UTC, neriheredia commented on components/NavBar/index.tsx
> +]
Crearía una carpeta constantes y lo pondría ahí a los links, también los nombres los guardaría en constantes o un objeto así si alguna vez necesitas agregar uno nuevo o modificar lo hagas en un solo archivo

2023-01-19 10:28 UTC, neriheredia commented on components/NavBar/NavLink.tsx
> +}
Y si lo puedes ordenar en orden alfabético mejor, es más simple después para encontrar una propiedad para otro dev

2023-01-19 11:40 UTC, sampxcs commented on components/NavBar/NavLink.tsx
> +}
Dale buenisimo! ya me pongo en eso. saludos

2023-01-23 00:41 UTC, neriheredia requested changes

2023-01-23 00:41 UTC, neriheredia commented on components/NavBar/index.tsx
> +          })}
¿Qué te parece un return implícito en esta ocasión?  Ejemplo: 

{navBarLinks.map(({ ...Props }) => (
         <NavLink key={name} path={path} onClick={handleCloseNav} buttonStyle={buttonStyle}>
                {name}
         </NavLink>
)}

2023-01-23 00:44 UTC, neriheredia commented
![Captura de pantalla de 2023-01-22 21-42-49](https://user-images.githubusercontent.com/82787982/213949463-d8c235dd-9eee-49cc-adc8-f10159a67281.png)

Mira en tablet se está rompiendo el diseño, podríamos hacer que unos píxeles antes ya pasemos a la versión de hamburguesa en el menú. ¿Qué te parece?

2023-01-27 01:04 UTC, neriheredia approved these changes

2023-02-10 20:17 UTC, closed without merging