Plat 29 seccion comentarios landing page
ProgramadoresArgentina/proyecto-ada pull request #17
Opened 2023-02-10 21:14 UTC by SmaelNicolas

# Descripción

Created comments section. Displays all comments in a marquee

## Jira

https://programadores-argentina.atlassian.net/jira/software/projects/PLAT/boards/1?selectedIssue=PLAT-29

2023-02-10 23:17 UTC, JuanseMastrangelo requested changes
@SmaelNicolas le faltan los test unitarios

2023-02-18 00:20 UTC, JuanseMastrangelo approved these changes

2023-02-18 01:31 UTC, sampxcs approved these changes

2023-02-18 01:32 UTC, sampxcs approved these changes

2023-02-28 14:26 UTC, JuanseMastrangelo commented on components/CommentsSection/CommentsSection.tsx
> +const velocity = 18;
Cuando son constantes globales se utilizan mayusculas y _ para separar palabras. Lo usaste bien en LGSIZE falto VELOCITY.

2023-02-28 14:53 UTC, JuanseMastrangelo approved these changes

2023-02-28 20:39 UTC, merged