Plat 27 crear vista de formulario para la generacion de cv
ProgramadoresArgentina/proyecto-ada pull request #40
Opened 2023-04-14 22:43 UTC by DanMartinez01

# Descripción

Incluya un resumen del cambio y qué problema se solucionó.

## Jira

- Agregar link de la tarjeta del _JIRA_ asociada.

* Link: https://programadores-argentina.atlassian.net/jira/software/projects/PLAT/boards/1?selectedIssue=PLAT-27

## Recuerde

- Borrar descripciones de secciones del _template_ para mayor orden en su _pull request_. Esto incluye esta sección.
- Agregar el label de _documentación_ en la _pull request_.
- Si su _pull request_ ya fue aprobada por alguien del equipo, incluir en el _ticket_ Jira la etiqueta.

2023-04-15 00:14 UTC, DevMartinese approved these changes

2023-04-15 20:28 UTC, neriheredia requested changes

2023-04-15 20:28 UTC, neriheredia commented on components/FormComponents/AddBtn.tsx
> +        >
Podrias ordenar alfabéticamente Dani por favor a las props

2023-04-15 20:28 UTC, neriheredia commented on components/FormComponents/DowloadFormBtn.tsx
> +        >
igual aquí

2023-04-15 20:28 UTC, neriheredia commented on components/FormComponents/DownloadSampleBtn.tsx
> +        >
Aqui también por favor

2023-04-15 20:28 UTC, neriheredia commented on components/FormComponents/DownloadSampleBtn.tsx
> +                    />
igual aquí

2023-04-15 20:28 UTC, neriheredia commented on components/FormComponents/RemoveBtn.tsx
> +        >
Aquí también

2023-04-15 20:28 UTC, neriheredia commented on components/FormComponents/SaveBtn.tsx
> +        >
Aquí también

2023-04-15 20:28 UTC, neriheredia commented on pages/generarcv.tsx
> +                        alt="cv"
Aquí en los componentes Image por favor

2023-04-15 20:28 UTC, neriheredia commented on schemas/basicSchema.tsx
> +            //   name: Yup.string().required("Name required"),
Podríamos borrar los comentarios

2023-04-20 01:26 UTC, JuanseMastrangelo approved these changes

2023-05-03 00:57 UTC, closed without merging